name: Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: actions/checkout@v5
      - run: npm install
      
      - name: Test
        run: npm run test

      
